Fix errors in php 7.4 (probably the first batch)
thebuggenie/thebuggenie pull request #566
Opened 2020-10-22 13:59 UTC by tatankat

2020-10-29 13:15 UTC, zegenie requested changes
Thanks for taking the time to post this. Could you have a look at the suggestions and let me know your thoughts?

2020-10-29 13:15 UTC, zegenie commented on core/framework/Settings.php
> +                return ($setting !== null?$setting[$uid]:null);
you can use `return $setting[$uid] ?? null` here instead.

2020-10-29 13:15 UTC, zegenie commented on core/modules/main/templates/_comments.inc.php
> +    <?php include_component('main/commentlist', compact('comment_count_div', 'mentionable_target_type', 'target_type', 'target_id', isset($issue)?'issue':array())); ?>
it's cleaner to add `if (!isset($this->issue)) $this->issue = null;` in the method `componentComments()`

2020-10-29 13:15 UTC, zegenie commented on core/modules/main/templates/_issue_workflow_transition.inc.php
> +                <?php include_component($transition->getTemplate(), compact('issue', 'transition', isset($ajax)?'ajax':array())); ?>
it's preferrable to initialize with empty values in the associated `componentX()` method, so you don't have to do these checks everywhere. 
```
if (!isset($this->ajax)) $this->ajax = null;
```
in the component method should do it.

2020-10-29 13:15 UTC, zegenie commented on core/modules/main/templates/_reportissuecontainer.inc.php
> +        <?php include_component('main/reportissue', compact('selected_project', isset($issue)?'issue':array(), 'issuetypes', 'selected_issuetype', 'selected_milestone', 'selected_build', 'parent_issu
See previous comments about initializing the methods in the associated component method

2020-10-29 13:15 UTC, zegenie commented on core/modules/main/templates/login.html.php
> +            <?php include_component('main/login', compact('section', isset($error)?'error':array())); ?>
See previous comments about initializing the methods in the associated component method

2020-10-29 13:15 UTC, zegenie commented on modules/publish/templates/_leftmenu.inc.php
> +    <?php include_component('publish/tools', compact(isset($special)?'special':array(), 'article')); ?>
See previous comments about initializing the methods in the associated component method

2020-11-03 20:27 UTC, tatankat commented
It's indeed cleaner that way (I wouldn't have found out, even if I was not doing some quick fixes while waiting for pachno ;) )
I cleaned up the commits and simply removed the magic quotes code as TBG does not support php 7 anymore.

2020-11-16 06:54 UTC, zegenie approved these changes

2020-11-16 06:54 UTC, merged